In [1]:
import numpy as np
import pandas as pd

In [2]:

from sklearn.datasets import load_boston

In [3]:
boston = load_boston()

boston.keys()


dict_keys(['data', 'target', 'feature_names', 'DESCR', 'filename'])

In [4]:
data = boston["data"]

data.shape

(506, 13)

In [5]:
feature_names = boston["feature_names"]

feature_names

array(['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD',
       'TAX', 'PTRATIO', 'B', 'LSTAT'], dtype='<U7')

In [6]:
X = pd.DataFrame(data, columns=feature_names)

X.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  
0     15.3  396.90   4.98  
1     17.8  396.90   9.14  
2     17.8  392.83   4.03  
3     18.7  394.63   2.94  
4     18.7  396.90   5.33

In [7]:
target = boston["target"]

In [8]:
y = pd.DataFrame(target, columns=["target"])

y.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 1 columns):
target    506 non-null float64
dtypes: float64(1)
memory usage: 4.0 KB


In [9]:
from sklearn.model_selection import train_test_split

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42,test_size=0.3)

In [11]:
from sklearn.linear_model import LinearRegression

In [12]:
lr = LinearRegression()

In [13]:
lr.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [14]:
y_pred = lr.predict(X_test)

y_pred.shape

(152, 1)

In [15]:
check_test = pd.DataFrame({
    "y_test": y_test["target"],
    "y_pred": y_pred.flatten(),
})

check_test.head(10)

y_test     y_pred
173    23.6  28.648960
274    32.4  36.495014
491    13.6  15.411193
72     22.8  25.403213
452    16.1  18.855280
76     20.0  23.146689
316    17.8  17.392124
140    14.0  14.078599
471    19.6  23.036927
500    16.8  20.599433

In [16]:
check_test["error"] = check_test["y_pred"] - check_test["y_test"]

check_test.head()

y_test     y_pred     error
173    23.6  28.648960  5.048960
274    32.4  36.495014  4.095014
491    13.6  15.411193  1.811193
72     22.8  25.403213  2.603213
452    16.1  18.855280  2.755280

In [17]:
from sklearn.metrics import mean_squared_error

mean_squared_error(check_test["y_pred"], check_test["y_test"])

21.517444231176995

In [18]:
from sklearn.metrics import r2_score #!!!!!!!!!!!!!!!!!!

In [19]:
r2=r2_score(y_test,y_pred)

In [20]:
r2


0.711226005748496

task 2

In [21]:
from sklearn.ensemble import RandomForestRegressor;
from sklearn.ensemble import RandomForestClassifier;

In [22]:
clf=RandomForestRegressor(n_estimators=1000,max_depth=12,random_state=42)


In [23]:
clf

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=12,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=1000, n_jobs=None,
           oob_score=False, random_state=42, verbose=0, warm_start=False)

In [24]:
X_train1=X_train.values[:]

In [25]:
y_train1=y_train.values[:,0]

In [26]:
y_train1


array([28.7, 21.2, 19.3, 23.1, 19.1, 25. , 33.4,  5. , 29.6, 18.7, 21.7,
       23.1, 22.8, 21. , 48.8, 14.6, 16.6, 27.1, 20.1, 19.8, 21. , 41.3,
       23.2, 20.4, 18.5, 29.4, 36.4, 24.4, 11.8, 13.8, 12.3, 17.8, 33.1,
       26.7, 13.4, 14.4, 50. , 22. , 19.9, 23.8, 17.5, 12.7,  5.6, 31.1,
       26.2, 19.4, 16.7, 13.8, 22.9, 15.3, 27.5, 36.1, 22.9, 24.5, 25. ,
       50. , 34.9, 31.7, 24.1, 22.1, 14.1, 42.8, 19.3, 32.2, 26.4, 21.8,
       21.7,  8.3, 46.7, 43.1, 31.5, 10.5, 16.7, 20. , 33.3, 17.8, 50. ,
       20.5, 23.2, 13.1, 19.6, 22.8, 28.7, 30.7, 22.9, 21.9, 23.9, 32.7,
       24.3, 21.5, 24.6,  8.5, 26.4, 23.1, 15. ,  8.8, 19.3, 23.9, 24.7,
       19.8, 23.8, 13.3, 29. , 27.1, 34.6, 13.3, 15.6, 12.5, 14.6, 11. ,
       24.8, 17.3,  8.1, 21.4, 15.6, 23.3, 32. , 38.7, 30.1, 20.5, 32.5,
       42.3, 24.3, 20.6, 22. , 18.2, 15. ,  6.3, 20.1, 21.4, 28.4, 30.1,
       20.8, 23. , 14.3, 11.7, 37.3, 17.1, 10.4, 23. , 22.7, 20.3, 21.7,
       50. ,  8.4, 18.8, 37.2, 16.1, 16.5, 22.2, 20

In [27]:
from sklearn.preprocessing import StandardScaler

In [28]:
ss=StandardScaler()

In [29]:
X_train_scaled=ss.fit_transform(X_train)

In [30]:
X_train_scaled


array([[-0.41425879, -0.50512499, -1.29214218, ...,  0.18727079,
         0.39651419, -1.01531611],
       [-0.40200818, -0.50512499, -0.16208345, ..., -0.21208981,
         0.3870674 , -0.05366252],
       [-0.39721053, -0.50512499, -0.60948856, ..., -0.16771641,
         0.42854113, -0.31132373],
       ...,
       [-0.41604586,  3.03838247, -1.3166773 , ..., -0.56707702,
         0.35987906, -0.90549329],
       [ 0.92611293, -0.50512499,  1.00549958, ...,  0.8528718 ,
        -2.87841346,  1.52750437],
       [-0.39030549, -0.50512499, -0.37135358, ...,  1.16348561,
        -3.32828832, -0.25218837]])

In [41]:
clf.fit(X_train, y_train1) 

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=12,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=1000, n_jobs=None,
           oob_score=False, random_state=42, verbose=0, warm_start=False)

In [40]:
?RandomForestRegressor


До конца не сделал , попробую в майские добить

In [42]:
X_test1=X_test.values[:]
y_test1=y_test.values[:,0]

In [44]:
y_test1


array([23.6, 32.4, 13.6, 22.8, 16.1, 20. , 17.8, 14. , 19.6, 16.8, 21.5,
       18.9,  7. , 21.2, 18.5, 29.8, 18.8, 10.2, 50. , 14.1, 25.2, 29.1,
       12.7, 22.4, 14.2, 13.8, 20.3, 14.9, 21.7, 18.3, 23.1, 23.8, 15. ,
       20.8, 19.1, 19.4, 34.7, 19.5, 24.4, 23.4, 19.7, 28.2, 50. , 17.4,
       22.6, 15.1, 13.1, 24.2, 19.9, 24. , 18.9, 35.4, 15.2, 26.5, 43.5,
       21.2, 18.4, 28.5, 23.9, 18.5, 25. , 35.4, 31.5, 20.2, 24.1, 20. ,
       13.1, 24.8, 30.8, 12.7, 20. , 23.7, 10.8, 20.6, 20.8,  5. , 20.1,
       48.5, 10.9,  7. , 20.9, 17.2, 20.9,  9.7, 19.4, 29. , 16.4, 25. ,
       25. , 17.1, 23.2, 10.4, 19.6, 17.2, 27.5, 23. , 50. , 17.9,  9.6,
       17.2, 22.5, 21.4, 12. , 19.9, 19.4, 13.4, 18.2, 24.6, 21.1, 24.7,
        8.7, 27.5, 20.7, 36.2, 31.6, 11.7, 39.8, 13.9, 21.8, 23.7, 17.6,
       24.4,  8.8, 19.2, 25.3, 20.4, 23.1, 37.9, 15.6, 45.4, 15.7, 22.6,
       14.5, 18.7, 17.8, 16.1, 20.6, 31.6, 29.1, 15.6, 17.5, 22.5, 19.4,
       19.3,  8.5, 20.6, 17. , 17.1, 14.5, 50. , 14

In [45]:
y_pred1 = clf.predict(X_test1)

In [46]:
y_pred1

array([22.84613791, 31.15611352, 16.29722565, 23.82103598, 17.21214765,
       21.82009184, 19.86636868, 14.75993798, 21.2352238 , 20.88310344,
       20.11747257, 19.98569932,  8.04139649, 21.47152808, 19.36056421,
       25.22123965, 18.86267442,  8.48509459, 45.8517    , 15.50158646,
       24.38461149, 23.98476408, 14.54325214, 23.5866156 , 15.02972553,
       15.26939983, 21.56389708, 13.95762333, 19.62523439, 21.0338126 ,
       19.6773222 , 23.23122956, 30.04524357, 20.12497811, 14.40836619,
       16.0512163 , 34.29058623, 19.18070898, 21.11179576, 24.23279505,
       18.63348333, 29.54059089, 45.5721    , 19.62260746, 22.57463812,
       13.9461684 , 15.72148872, 24.47776906, 19.12640766, 28.25341645,
       21.36055927, 33.88579611, 17.70003733, 26.2955691 , 45.52367393,
       21.87518392, 15.85920641, 32.42684361, 22.15625161, 20.61280516,
       25.46784804, 33.69946617, 30.09116874, 19.02315904, 27.12221893,
       16.92785667, 13.87709764, 23.11178339, 28.86580833, 15.60

In [47]:
r2_1=r2_score(y_test1,y_pred1)

In [48]:
r2_1

0.8749965273218174

#### ***r2_1 > r2 точность предсказаний у RandomForestRegressor выше , следовательно модель лучше

In [55]:
clf.feature_importances_

array([0.03211748, 0.00154999, 0.0070941 , 0.0011488 , 0.01436832,
       0.40270459, 0.01424477, 0.06403265, 0.00496762, 0.01169177,
       0.01808961, 0.0123114 , 0.41567892])

In [66]:
a=sum(clf.feature_importances_)

In [67]:
a

0.9999999999999993

In [92]:
b=zip(clf.feature_importances_,feature_names)

In [93]:
b

In [94]:
c=list(b)

In [98]:
c.sort(reverse=1)

In [99]:
list(c)

[(0.41567892145099405, 'LSTAT'),
 (0.4027045916967308, 'RM'),
 (0.06403265381454108, 'DIS'),
 (0.03211747801029037, 'CRIM'),
 (0.018089605464908644, 'PTRATIO'),
 (0.014368315731541823, 'NOX'),
 (0.014244766864655395, 'AGE'),
 (0.01231139582996545, 'B'),
 (0.01169176862189803, 'TAX'),
 (0.007094098492215249, 'INDUS'),
 (0.0049676188426270645, 'RAD'),
 (0.0015499893488862247, 'ZN'),
 (0.0011487958307451881, 'CHAS')]